;
; CH552G Keyboard — PlatformIO Build Configuration
;
; Targets:
;   pio run -e board          Build firmware
;   pio run -e board -t upload  Upload firmware
;   pio run -e app            Build Windows configurator app
;

[env:board]
platform = ./platform/ch552
board = ch552g
framework = arduino
lib_ignore = JQB
build_flags =
    -DUSER_USB_RAM=148
    -Isrc/shared
build_src_filter =
    -<*>
    +<board/>
    +<board/userUsbHidKeyboard/>
    +<../../../.platformio/packages/framework-ch55xduino/ch55x/libraries/WS2812/src/WS2812.c>
    +<../../../.platformio/packages/framework-ch55xduino/ch55x/libraries/WS2812/src/template/optionalLink_WS2812_P3_4.c>

[env:app]
platform = native
lib_deps =
    https://github.com/JAQUBA/JQB_WindowsLib.git
build_flags =
    -Isrc/shared
    -Isrc/app
build_src_filter =
    -<*>
    +<app/>